projects:
  workoutTracker:
    schemaPath: amplify/backend/api/workoutTracker/build/schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: ap-southeast-2
        maxDepth: 2
